apiVersion: batch/v1
kind: Job
metadata:
  generateName: mlas-coursework-
  labels:
    kueue.x-k8s.io/queue-name:  eidf018ns-user-queue
    eidf/user: "YOUR_EIDF_USERNAME"
spec:
  completions: 1
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: interactive-gpu-access
    spec:
      activeDeadlineSeconds: 99600
      containers:
      - name: pytorch
        stdin: true
        image: registry.eidf.ac.uk/eidf018/pytorch:2.10.0-cuda12.8-cudnn9-devel 
        imagePullPolicy: Always 
        args: ["/bin/bash"]
        resources:
          requests:
            cpu: 20
            memory: '64Gi'
            nvidia.com/gpu: 2
          limits:
            cpu: 20
            memory: '64Gi'
            nvidia.com/gpu: 2
        volumeMounts:
          - mountPath: /mnt/pvc
            name: volume
          - mountPath: /mnt/shared
            name: volume2
          - mountPath: /dev/shm
            name: dshm
      restartPolicy: Never
      imagePullSecrets:
        - name: eidfreg-YOUR_EIDF_USERNAME
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: YOUR_EIDF_USERNAME-mlas-pvc
        - name: volume2
          persistentVolumeClaim:
            claimName: mlas-shared-pvc
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 32Gi
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB
